### ISSUE TITLE
Sreeja Gangapuram: Data Structures Individual Project Plan (Backend and Leaderboard Focused) 

### ISSUE THREAD

**Issue by sreejagangapuram** [sreejagangapuram/sreejagangg#13]
### **Objective: Backend Unification and Functional Leaderboard**
1. I will work with Tirth Takkar on the backend unification of our two projects. 

Action Items: 

- [ ] will change the person POJO in the backends of the farming and basketball systems so that it operates under a single login system.
- [ ]  will study and include Basketball API capabilities into the unified backend to guarantee that it works together 
- [ ] will make an effort to comprehend the linear regression model in order to preserve functionality that is essential to the basketball backend.

2. Functional leaderboard 

Action Items:

- [ ] Clean up the formatting
- [ ] Columns should be the following: Username, Cash, any other relevant nba bet params 
- [ ] accessing data from both sides of backend
- [ ] will be on a seperate html page under the combined frontend

3. Group Leadership 

Action Items:

- [ ] Keep Scrum Board updated 
- [ ] supervise discord messaging and announcements 
- [ ] make sure all members in period 3 are working 

### **Weekly Plan**
Monday (Planning Day) 
- was home sick :) 
- but hopped on a call with haseeb and vinay in order to debrief and brainstorm our leaderboard feature 
- worked on planning and this issue 

Tuesday 
- make a new html page for the leaderboard 
- will change the person POJO in the backends of the farming and basketball systems so that it operates under a single login system.

Wednesday 
- will study and include Basketball API capabilities into the unified backend to guarantee that it works together 
- update scrum board mid week 
- group call at 7pm!!

Thursday
- study linear regression model of the basketball backend and attempt to integrate it into ours 
- Columns should be the following: Username, Cash, any other relevant nba parameters 
- accessing data from both sides of backend

Friday 
- update scrum board 
- weekly group meeting 
- catchup on any action items not completed

Weekend 
- job interview assignment prep
